services:
  - type: web
    name: a1-core-engine
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - type: redirect
        source: /*
        destination: /index.html
